### ISSUE TITLE
HTTP images added by Feedburner

### ISSUE THREAD

**Issue by davorg** [szabgab/perlweekly#299]
Planet Perl is served over HTTPS, but that's always difficult for an aggregator because you're likely to pull HTTP image links in from one of your sources (which will generate "mixed content" warnings and remove the images).

I noticed I lot of mixed content warnings coming from entries from Perl Weekly, so I forked the repo, planning to fix the problem. But it seems that these are 1x1 tracking pixels that are added by FeedBurner. Annoyingly, even when I request the FeedBurner feed over HTTPS, I still get HTTP images in the feed. Which is rather broken.

I'm hoping that you can flick a FeedBurner option somewhere that will serve all of their tracking pixels over HTTPS. But I strongly suspect that it's a bug in FeedBurner.

**Comment by davorg** [comment]
I just spend five minutes Googling this problem and poking around in my (long unused) Feedburner dashboard. And it seems that FeedBurner has been unsupported since long before HTTPS took over the web. So I'd recommend not using it. Either go back to your raw web feed or find a replacement that is still kept up to date. Do you really get useful information from it?

**Comment by szabgab** [comment]
Yeah, we should stop using it. Now if I could find how does it work :)

**Comment by szabgab** [comment]
Oh found it, we have a perlweekly.rss

**Comment by szabgab** [comment]
https://perlweekly.com/perlweekly.rss

**Comment by davorg** [comment]
Yeah. Already found that, thanks :-)

**Comment by szabgab** [comment]
I have replaced the links on all the perlweekly site to point our internal rss feed instead of the feedburner.
Thanks for raising the issue. This was a long due fix.

If I understand correctly people who rely on the old FeedBurner feed will still be able to use it.
