### ISSUE TITLE
More useful RSS

### ISSUE THREAD

**Issue by davorg** [szabgab/perlweekly#368]
Currently, the RSS feed that you generate only contains details of the current issue. And it contains an entry for each article in the issue. This means that your RSS feed is published, Planet Perl (https://perl.theplanetarium.org/) gets a new entry for each article in the new issue. This is a problem for a couple of reasons:

* Everything else in the feed is pumped down about 25 places, so Perl Weekly monopolies the web page.
* The articles you feature will have usually already appeared on Planet Perl when they were published at some point in the previous week.

I'd like to suggest that you also publish an alternative RSS feed that only contains the introduction article for each week. It could also contain the last five or ten issues of Perl Weekly. I think that would be a more traditional use of RSS and would avoid clogging up Planet Perl once a week :-)

It would also have the advantage that people would need to click through to your site to read the rest of the newsletter.

Let me know what you think.

**Comment by szabgab** [comment]
Sounds like a good idea. Will you implement it?

**Comment by davorg** [comment]
I can take a look and see how hard it'll be :-)

**Comment by davorg** [comment]
Closed the original PR and recreated it at https://github.com/szabgab/perlweekly/pull/374

**Comment by szabgab** [comment]
As far as I understand this @davorg has implemented it and it has been deployed. Thank you!
