### ISSUE TITLE
I'll copy edit, if no-one else volunteers

### ISSUE THREAD

**Issue by hbarnard** [szabgab/perlweekly#441]
Be in contact if/as and when. Hugh B

**Comment by szabgab** [comment]
Thanks, let's email

**Comment by szabgab** [comment]
Sorry for the late reply. There were a number of people who volunteers and I got a bit busy with some other project.
David Precious had an excellent suggestion to open an issue for each edition of the PW when it is ready for copy-editing and to mention all the volunteers. Then the first who has time that week can do the copy-editing and this also provides a platform for them to make sure there is no duplicate work. So I am going to try that today.

**Comment by hbarnard** [comment]
No problem, meanwhile I'm afraid I've taken a freelance gig offered suddenly. Cost of living is rising fast in the UK, so I've taken it. All the best Hugh

---------
https://www.hughbarnard.org
Twitter: @hughbarnard

------- Original Message -------
