### ISSUE TITLE
copy editing 555

### ISSUE THREAD

**Issue by szabgab** [szabgab/perlweekly#445]
The new Perl Weekly edition is ready for copy-editing. If you have the time to do it,
please comment on this issue so the others will see that someone already works on it and we
avoid duplicate work and conflicting PRs. If you'd like to de-volunteer, please tell @szabgab
so next time he won't include you. Thank you.

@bigpresh, @hbarnard, @jjatria, @knowledgejunkie, @matthewpersico

Please only edit the source file:

https://github.com/szabgab/perlweekly/blob/master/src/555.json

**Comment by bigpresh** [comment]
Doesn't look like anyone else is jumping in so I'll give it a review now, PR coming shortly.

**Comment by matthewpersico** [comment]
I am sorry. I did not know I was going to be on the reviewers list. I will make sure I check my email for next week.
