### ISSUE TITLE
Is it possible to add lu.ma events to the feed?

### ISSUE THREAD

**Issue by oalders** [szabgab/perlweekly#569]
Toronto.pm recently switched from meetup.com to lu.ma: https://lu.ma/giz69577 It looks like there is some kind of iCal output here: https://api.lu.ma/ics/get?entity=calendar&id=cal-ZFzHes2YwV6j0h9

My immediate concern would be getting our new events listed and the meetup events removed. Should that be done with a manual PR on `src/events.json`?

CC @talexb

**Comment by szabgab** [comment]
manual pr, please
